"""
SOMNIA Configuration File
Team: Chimpanzini Bananini
"""

import os

# API Configuration
API_VERSION = "0.1.0"
API_TITLE = "SOMNIA API"
API_DESCRIPTION = "Comprehensive Sleep Health Monitoring System - Multimodal AI"

# Database Configuration
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./somnia.db")

# Security
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key-change-in-production")
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60

# Environment
DEBUG = os.getenv("DEBUG", "True").lower() == "true"
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

# CORS
ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://localhost:19000",
    "http://localhost:19002",
]

# File Upload
UPLOAD_DIR = os.path.join(os.getcwd(), "uploads")
MAX_UPLOAD_SIZE = 100 * 1024 * 1024  # 100MB

# AI/ML Configuration
MODEL_PATH = os.path.join(os.getcwd(), "models")
AUDIO_SAMPLE_RATE = 16000
AUDIO_DURATION = 480  # 8 hours in seconds equivalent

# Snoring Detection (adrianagaler/Snoring-Detection) integration
# Provide paths to the frozen TF graph (.pb) and labels file generated by the
# Snoring-Detection training pipeline (freeze.py). By default, we look under
# backend/models/snoring.
SNORING_MODEL_DIR = os.path.join(os.getcwd(), "backend", "models", "snoring")
SNORING_GRAPH_PATH = os.getenv(
    "SNORING_GRAPH_PATH",
    os.path.join(SNORING_MODEL_DIR, "snoring_frozen_graph.pb"),
)
SNORING_LABELS_PATH = os.getenv(
    "SNORING_LABELS_PATH",
    os.path.join(SNORING_MODEL_DIR, "labels.txt"),
)

SNORING_INPUT_TENSOR = os.getenv("SNORING_INPUT_TENSOR", "wav_data:0")
SNORING_OUTPUT_TENSOR = os.getenv("SNORING_OUTPUT_TENSOR", "labels_softmax:0")

# Feature flags (default off so nothing changes unless explicitly enabled)
ENABLE_SNORING = os.getenv("ENABLE_SNORING", "false").lower() == "true"
ENABLE_VIDEO_POSE = os.getenv("ENABLE_VIDEO_POSE", "false").lower() == "true"
ENABLE_ML_MODELS = os.getenv("ENABLE_ML_MODELS", "false").lower() == "true"

# ML Model Paths
SPO2_MODEL_PATH = os.getenv("SPO2_MODEL_PATH", os.path.join(os.path.dirname(__file__), "models", "SpO2_weights.hdf5"))
ECG_MODEL_PATH = os.getenv("ECG_MODEL_PATH", os.path.join(os.path.dirname(__file__), "models", "ecg_weights.hdf5"))

print(f"SOMNIA Configuration Loaded - Environment: {ENVIRONMENT}")