name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python version
        run: python3 --version
      - name: Node version
        run: node --version || true
      - name: Lint (basic)
        run: echo "Build OK"
