name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal backend deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic numpy pytest httpx
      - name: Run backend tests
        run: pytest -q backend/tests
